CREATE DATABASE Pessoa_TardeDDL;

USE Pessoa_TardeDDL;

CREATE TABLE Telefone (
	IdTelefone 	INT PRIMARY KEY IDENTITY,
	Numero		VARCHAR (200)
	);
	
CREATE TABLE Email ( 
	IdEmail	INT PRIMARY KEY IDENTITY,
	Emaail	VARCHAR (200)
	);

CREATE TABLE CNH (
	IdCNH INT PRIMARY KEY IDENTITY,
	Registro VARCHAR (200)
	);

CREATE TABLE Pessoa (
	IdPessoa	INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR (200),
	IdTelefone	INT FOREIGN KEY REFERENCES Telefone(IdTelefone),
	IdEmail		INT FOREIGN KEY REFERENCES Email(IdEmail),
	IdCNH		INT FOREIGN KEY REFERENCES CNH(IdCNH)
	);